{
    "openapi": "3.0.1",
    "info": {
        "title": "API locadora de carros",
        "description": "Uma API que tem como objetivo criar e manipular carros, pessoas e faz autenticação delas",
        "termsOfService": "http://localhost:3000/terms",
        "contact": {
            "email": "luizboldriniej@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3000/api/v1",
            "description": "API local"
        }
    ],
    "paths": {
        "/authenticate": {
            "post": {
                "summary": "Faz a autenticação dos usuários",
                "description": "Esta rota será responsável pela autenticação de usuários cadastrados",
                "tags": ["Authenticate"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "example": "joazinho@email.com"
                                    },
                                    "password": {
                                        "type": "string",
                                        "example": "123456"
                                    }
                                }
                            }
                        }
                    }
                },
                 "responses": {
                    "201": {
                        "description": "Authenticate",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "token": {
                                            "type": "string"
                                          },
                                        "email": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/car": {
            "post": {
                "summary": "Cadrasto de carros",
                "description": "Esta rota será responsável pelo cadrasto de carros",
                "tags": ["Car"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Car"
                            },
                            "examples": {
                                "car": {
                                    "value": {
                                        "model": "Hilux",
                                        "type": "SuV",
                                        "brand": "GM",
                                        "color": "Amarelo",
                                        "year": 2001,
                                        "accessories": [
                                            {
                                                "description": "Diesel"
                                            },
                                            {
                                                "description": "Teto solar"
                                            },
                                            {
                                                "description": "Automático"
                                            }
                                        ],
                                        "passengersQtd": 4
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Car"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            },
            "get": {
                "summary": "Listagem de carros",
                "description": "Está rota irá listar todos os carros por parâmetro",
                "tags": ["Car"],
                "parameters": [{
                    "name": "model",
                    "in": "qurey",
                    "description": "Model do carro para busca"
                },
                {
                    "name": "type",
                    "in": "qurey",
                    "description": "Type do carro para busca"
                },
                {
                    "name": "brand",
                    "in": "qurey",
                    "description": "Brand do carro para busca"
                },
                {
                    "name": "color",
                    "in": "qurey",
                    "description": "Color do carro para busca"
                },
                {
                    "name": "year",
                    "in": "qurey",
                    "description": "Year do carro para busca"
                },
                {
                    "name": "passengersQtd",
                    "in": "qurey",
                    "description": "Quantidade de passageiros do carro para busca"
                }
            ],
            "responses": {
                "200": {
                    "description": "Good Request",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Car"
                                    }
                                }
                            }
                        }
                },
                "400": {
                    "description": "Bad Request"
                } 
            }
            }
        },
        "/car/{id}": {
            "get": {
                "summary": "Listagem de carros pelo ID",
                "description": "Está rota irá listar o carro pelo ID indicado",
                "tags": ["Car"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "description": "Busca um carro pelo ID",
                    "required": true
                }
            ],
            "responses": {
                "200": {
                    "description": "Good Request",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Car"
                                }
                            }
                        }
                },
                "400": {
                    "description": "Bad Request"
                },
                "404": {
                    "description": "Not found"
                }
            }
            },
            "put": {
                "summary": "Atualiza um carro pelo ID",
                "description": "Está rota irá atualizar dados do carro pelo ID indicado",
                "tags": ["Car"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "description": "Busca um carro pelo ID",
                    "required": true
                }
            ],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Car"
                        },
                        "examples": {
                            "car": {
                                "value": {
                                    "model": "S10 2.8",
                                    "type": "SuV",
                                    "brand": "GM",
                                    "color": "Amarelo",
                                    "year": 2001,
                                    "accessories": [
                                        {
                                            "description": "Diesel"
                                        },
                                        {
                                            "description": "Teto solar"
                                        },
                                        {
                                            "description": "Automático"
                                        }
                                    ],
                                    "passengersQtd": 4
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "204": {
                    "description": "Good Request"
                },
                "400": {
                    "description": "Bad Request"
                },
                "404": {
                    "description": "Not found"
                }
            } 
            },
            "delete": {
                "summary": "Apaga um carro pelo ID",
                "description": "Está rota irá apagar o carro pelo ID indicado",
                "tags": ["Car"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "description": "Busca um carro pelo ID",
                    "required": true
                }
            ],
            "responses": {
                "204": {
                    "description": "Good Request"
                },
                "400": {
                    "description": "Bad Request"
                },
                "404": {
                    "description": "Not found"
                }
            }
            }
        },
        "/person": {
            "post": {
                "summary": "Cadrasto de pessoas",
                "description": "Esta rota será responsável pelo cadrasto das pessoas",
                "tags": ["Person"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Person"
                            },
                            "examples": {
                                "car": {
                                    "value": {
                                        "name": "Joãozinho Silva",
                                        "cpf": "04126271244",
                                        "birthDay": "10-02-2000",
                                        "email": "joazinho@email.com",
                                        "password": "123456",
                                        "canDrive": "yes"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Person"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            },
            "get": {
                "summary": "Listagem de pessoas",
                "description": "Está rota irá listar todas as pessoas por parâmetro",
                "tags": ["Person"],
                "parameters": [{
                    "name": "name",
                    "in": "qurey",
                    "description": "Name do carro para busca"
                },
                {
                    "name": "cpf",
                    "in": "qurey",
                    "description": "cpf do carro para busca"
                },
                {
                    "name": "birthDay",
                    "in": "qurey",
                    "description": "birthDay do carro para busca"
                },
                {
                    "name": "email",
                    "in": "qurey",
                    "description": "email do carro para busca"
                },
                {
                    "name": "canDrive",
                    "in": "qurey",
                    "description": "canDrive do carro para busca"
                }
            ],
            "responses": {
                "200": {
                    "description": "Good Request",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Person"
                                    }
                                }
                            }
                        }
                },
                "400": {
                    "description": "Bad Request"
                } 
            }
        }
        },
        "/person/{id}": {
            "get": {
                "summary": "Listagem de pessoas pelo ID",
                "description": "Está rota irá listar uma pessoa pelo ID indicado",
                "tags": ["Person"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "description": "Busca uma pessoa pelo ID",
                    "required": true
                }
            ],
            "responses": {
                "200": {
                    "description": "Good Request",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Person"
                                }
                            }
                        }
                },
                "400": {
                    "description": "Bad Request"
                },
                "404": {
                    "description": "Not found"
                }
            }
            },
            "put": {
                "summary": "Atualiza uma pessoa pelo ID",
                "description": "Está rota irá atualizar dados de uma pessoa pelo ID indicado",
                "tags": ["Person"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "description": "Busca uma pessoa pelo ID",
                    "required": true
                }
            ],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Person"
                        },
                        "examples": {
                            "car": {
                                "value": {
                                    "name": "Joãozinho Silva",
                                    "cpf": "04126271244",
                                    "birthDay": "10-02-2000",
                                    "email": "joazinho@emai.com",
                                    "password": "123456",
                                    "canDrive": "yes"
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "204": {
                    "description": "Good Request"
                },
                "400": {
                    "description": "Bad Request"
                },
                "404": {
                    "description": "Not found"
                }
            } 
            },
            "delete": {
                "summary": "Apaga uma pessoa pelo ID",
                "description": "Está rota irá apagar uma pessoa pelo ID indicado",
                "tags": ["Person"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "description": "Busca uma pessoa pelo ID",
                    "required": true
                }
            ],
            "responses": {
                "204": {
                    "description": "Good Request"
                },
                "400": {
                    "description": "Bad Request"
                },
                "404": {
                    "description": "Not found"
                }
            }
            }
        },
        "/rental": {
            "post": {
                "summary": "Cadrasto de uma locadora",
                "description": "Esta rota será responsável pelo cadrasto de locadoras",
                "tags": ["Rental"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Rental"
                            },
                            "examples": {
                                "car": {
                                    "value": {
                                        "name": "Localiza Rent a Car",
                                        "cnpj": "16.670.085/0001-17",
                                        "activities": "Aluguel de Carros E Gestão de Frotas",
                                        "address": [
                                            {
                                                "zipCode": "96200-200",
                                                "number":"1234",
                                                "isFilial": true
                                            },
                                            {
                                                "zipCode": "76937-000",
                                                "number":"1234",
                                                "isFilial": false
                                            }]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Rental"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            },
            "get": {
                "summary": "Listagem de locadoras",
                "description": "Está rota irá listar todas as Locadoras por parâmetro",
                "tags": ["Rental"],
                "parameters": [{
                    "name": "name",
                    "in": "qurey",
                    "description": "Name da locadora para busca"
                },
                {
                    "name": "cnpj",
                    "in": "qurey",
                    "description": "Cnpj da locadora para busca"
                },
                {
                    "name": "activities",
                    "in": "qurey",
                    "description": "Activities da locadora para busca"
                }
            ],
            "responses": {
                "200": {
                    "description": "Good Request",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Person"
                                    }
                                }
                            }
                        }
                },
                "400": {
                    "description": "Bad Request"
                } 
            }
            }  
        },
        "/rental/{id}": {
            "get": {
                "summary": "Listagem de locadoras pelo ID",
                "description": "Está rota irá listar uma locadora pelo ID indicado",
                "tags": ["Rental"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "description": "Busca uma locadora pelo ID",
                    "required": true
                }
            ],
            "responses": {
                "200": {
                    "description": "Good Request",
                        "content":{
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Rental"
                                }
                            }
                        }
                },
                "400": {
                    "description": "Bad Request"
                },
                "404": {
                    "description": "Not found"
                }
            }
            },
            "put": {
                "summary": "Atualiza uma locadora pelo ID",
                "description": "Está rota irá atualizar dados de uma locadora pelo ID indicado",
                "tags": ["Rental"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "description": "Busca uma locadora pelo ID",
                    "required": true
                }
            ],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Rental"
                        },
                        "examples": {
                            "car": {
                                "value": {
                                    "name": "Localiza Rent a Car LtdA.",
                                        "cnpj": "16.670.085/0001-17",
                                        "activities": "Aluguel de Carros E Gestão de Frotas",
                                        "address": [
                                            {
                                                "zipCode": "96200-200",
                                                "number":"1234",
                                                "isFilial": true
                                            },
                                            {
                                                "zipCode": "76937-000",
                                                "number":"1234",
                                                "isFilial": false
                                            }]
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "204": {
                    "description": "Good Request"
                },
                "400": {
                    "description": "Bad Request"
                },
                "404": {
                    "description": "Not found"
                }
            } 
            },
            "delete": {
                "summary": "Apaga uma locadora pelo ID",
                "description": "Está rota irá apagar uma locadora pelo ID indicado",
                "tags": ["Rental"],
                "parameters": [{
                    "name": "id",
                    "in": "path",
                    "description": "Busca uma locadora pelo ID",
                    "required": true
                }
            ],
            "responses": {
                "204": {
                    "description": "Good Request"
                },
                "400": {
                    "description": "Bad Request"
                },
                "404": {
                    "description": "Not found"
                }
            }
            }
        }
    },
    "components": {
        "schemas": {
            "Car": {
                "type": "object",
                "properties": {
                    "_id": {
                        "type": "string"
                    },
                    "model": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "brand": {
                        "type": "string"
                    },
                    "color": {
                        "type": "string"
                    },
                    "year": {
                        "type": "number"
                    },
                    "accessories": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "description": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "passengersQtd": {
                        "type": "number"
                    }
                }
            },
            "Person": {
                "type": "object",
                "properties": {
                    "_id": {
                        "type": "string"
                    },"cpf": {
                        "type": "string"
                    },"birthDay": {
                        "type": "date"
                    },"email": {
                        "type": "string",
                        "unique": true
                    },"password": {
                        "type": "string",
                        "select": false
                    },"canDrive": {
                        "type": "string",
                        "enum": {
                            "values": ["yes", "no"]
                        }
                    }
                }
            },
            "Rental": {
                "type": "object",
                "properties": {
                    "_id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "cnpj": {
                        "type": "string",
                        "unique": true
                    },
                    "activities": {
                        "type": "string"
                    },
                    "address": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "zipCode": {
                                    "type": "string"
                                },
                                "street": {
                                    "type": "string"
                                },
                                "complement": {
                                    "type": "string"
                                },
                                "district": {
                                    "type": "string"
                                },
                                "number": {
                                    "type": "number"
                                },
                                "city": {
                                    "type": "string"
                                },
                                "state": {
                                    "type": "string"
                                },
                                "isFilial": {
                                    "type": "boolean"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}